### ISSUE TITLE
Remove unneeded files from git

### ISSUE THREAD

**Issue by canyon289** [hyosubkim/bayesian-statistics-toolbox#2]
DS_store, ipynb checkpoints, egg-info, should be removed from git, and added to the gitignore. Examples from PyMC gitignore are below.

Note. This may require the uuse of a repo cleaner

https://github.com/hyosubkim/bayesian-statistics-toolbox/tree/main/.ipynb_checkpoints
https://github.com/hyosubkim/bayesian-statistics-toolbox/tree/main/src.egg-info
https://github.com/pymc-devs/pymc/blob/main/.gitignore#L12

Note. This may require the use of a repo cleaner due to the way git works once file are committed
https://rtyley.github.io/bfg-repo-cleaner/

**Comment by hyosubkim** [comment]
Those files are now removed, as well as .pyc files. The are all on the .gitignore list now. Thanks!
