### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by canyon289** [hyosubkim/bayesian-statistics-toolbox#3]
Theres a section in the README but as more and more stuff gets added such as testing and linting this will expand. Itll be good to preemptively create one

https://github.com/hyosubkim/bayesian-statistics-toolbox#how-to-contribute-to-bst

**Comment by hyosubkim** [comment]
Good idea! Just created one: https://github.com/hyosubkim/bayesian-statistics-toolbox/blob/main/CONTRIBUTING.md
